language: node_js

node_js:
  - "8.11.4"

before_install:
  - npm i -g npm@6.4.0

install:
  - npm install

branches:
  only:
    - master # will only build for master branch commits

script:
  - npm run lint
  - npm test
